@extends("layout")
@section("content")
<style>
    </style>
    <div class="container">
        <div class="row">
          <div class="col-md-10 mx-auto">
            <h1 class="full-width text-center" style="margin-top: 150px;font-size: 46px; text-transform: uppercase; text-align: justify;">
                Unity University History
            </h1>
            <p class="lead full-width text-justify">
                <b>Unity University </b>is the pioneer private higher education institution in Ethiopia. Since its establishment as a Language School in 1991, has made tremendous progress to become the first privately owned university in the country. The University became member of MIDROC Technology Group Companies in 2008, and stayed so up to 2020.
            </p>
            <img src="{{asset("/images/unity_buying.png")}}" alt="Image" class="img-fluid my-4">
            <p class="lead full-width text-justify">
                <b>Unity University </b> started its long march by delivering certificate programs. Initially, it was established as a language school, offering courses in English, Arabic, Italian and French. Later, that same year, preparatory classes were opened for the then Ethiopian School Leaving Certificate Examination (E.S.L.C.E) in different subjects. Thus, the year 1991 marks the beginning of the first phase in the history of <b>Unity University </b>; a milestone that paved the way for the establishment and subsequent rapid expansion of the University.
                In fact, Unity Language School stared with few students and with a handful of part-time teachers and administrative workers. The School, however, grew rapidly over the next three years in many respects. The student population as well as the number of academic and administrative staff increased significantly. The coverage of the School also expanded through the addition of new courses; such as Certificate Program in Basic Law, in February 1993. In 1994, the Certificate Program in Basic Law was upgraded to a Diploma level.
                In 1993, the School opened a new branch outside of Addis Ababa, in Adama town of Oromia Regional State. Currently, the Adama Campus offers MBA, BA and BSc Degree Programs in Business and Computational Sciences.
                Furthermore, Vocational Courses in Business Administration, Food and Beverage Services, and Front Office Clerking commenced in 1997. The name of the School was changed to “Unity Law, Language and Vocational Institute” in order to reflect the continuous dynamism and changes that took place.
                Thus, the second phase that started in 1997 lasted up to 1998, during which time Diploma Programs in Accounting, Marketing, Business, Personnel Administration and Secretarial Science were launched. At this juncture the name “Unity Law, Language and Vocational Institute” became “Unity College”.
            </p>
                <p class="lead full-width text-justify">
                    In the year 1999 the third phase of the University’s development witnessed not only the consolidation of existing Diploma Programs but also a significant expansion in the range of programs offered; starting with the introduction of new undergraduate degree program in Accounting, Management, and Economics.
                BSc Degree Program in Management Information System (MIS) and Diploma Program in Journalism and Communication were launched in the year 2000; and additional undergraduate degree programs in Law, Marketing Management, and Computer Technology were made available to regular and extension degree students. In August 2002, “Unity College” was officially renamed “<b>Unity University </b> College”. Thus Unity becomes the first private “University College”.
                In 2003 a BSc Degree program in Architecture and Urban Planning was introduced. In addition to this, BSc Degree Programs were introduced in Civil Engineering, in Mining, and in Construction Technology Management.
                In this same year - 2003 College of Distance Education was established by offering Accounting, Management, Secretarial Science and Office Management, Business Administration, Marketing, Banking and Finance, and Law in Diploma Programs. Consequently, the Diploma Programs in Accounting, Management, Marketing and Economics were upgraded to a Degree Program.
                The fourth phase of the development of <b>Unity University </b> can be traced back to February 2007, when it launched two Postgraduate Programs, namely, Master of Business Administration and Master of Development Economics.
                In June, 2008, <b>Unity University </b> College became the first full-fledged University among the emerging private higher education institutions.
                </p>
                <p class="lead full-width text-justify">
                    As of November, 2008, <b>Unity University </b> became member of MIDROC Technology Group companies. After the University joined MIDROC Technology Group companies, its expansion increased further. The University stayed as member of TGC up to April, 2020, until Dr. Arega Yirdaw the President of the University, who has served simultaneously as the CEO of the TGC, cede the position of CEO of TGC and became the President and CEO of <b>Unity University </b>.
                In 2012, another branch campus was opened outside Addis Ababa, in Dessie town of Amhara Regional State. The campus offers undergraduate degree programs in Accounting and Finance, Business Administration and Computer Sciences.
                SalaM College of Health Sciences (SCHS) was inaugurated as ‘SalaM Nurses College’, under SalaM Health Care PLC in 1998, with the objective of training professional nurses at Diploma level. In 2011/12 the College was absorbed by <b>Unity University </b>. Currently, the College is renamed as ‘Health Sciences Faculty of <b>Unity University </b>’, and has moved from Kore to Al-Amoudi Campus, Gerji. At present, the Faculty offers Postgraduate Program in Public Health and Undergraduate Programs in Nursing, Public Health, and Medical Laboratory Sciences Technologies
                In 2016/17, another Campus was opened in Burayu, which currently accommodates, the University’s Printing, and Unity Academy Burayu Branch. The Campus used to offer undergraduate degree programs in Animal Production and Technology and Horticulture. It also offered Management, Marketing Management, and Accounting and Finance at undergraduate level, until 2020/21 academic year.
                As one of its core functions, <b>Unity University </b> encourages and conducts research. Since 2001, Unity has been holding Annual Multi-Disciplinary Research Conferences; without interruption, where scholars from different Universities research institutions and other establishments participate. The articles (papers) of each Annual Multidisciplinary Research Conference are published in the University’s Proceedings of the Conference, and in the University’s journal, entitled “Ethiopian Journal of Business and Development.”
                </p>
                <p class="lead full-width text-justify">
                    <b>Unity University </b> is also very active in community service programs. The University had offered scholarships to several students with financial difficulties.
                It also gives scholarships to its employees as staff development scheme. It benefits those who wish to upgrade their academic status. In addition to this, the University offers 15% Grant, as an encouragement for employees and family members of MIDROC Ethiopia Investment Group.
                Among the scholarship offers of the University, one was ‘<b>Unity University </b> Girls’ Education Project’, which was run by the University in collaboration with Sponsorship from Donner Organization. The Project extended its assistance to deserving girl students from around the country who could not peruse their tertiary education because of financial difficulties. The Project, until its closure in 2016, had helped more than 200 young girls to obtain their Undergraduate Degrees in the fields of their choice.
                Unity works closely with Ethiopian Red Cross Society in its life saving activity. Students voluntarily donate blood once or twice a year as required by the Society.
                Architecture and Urban Planning (AUP) Department of the University has been widely engaged in providing community services. The Department has planned and designed projects for different sites in Addis Ababa: Kassanchis, Uralel, Merkato, Hayat, Sumit CMC and other surrounding areas.
                </p>
                <p class="lead full-width text-justify">
                    The Department as well provided its services to 7 towns outside Addis Ababa in Oromia Region State, in towns like Sebata, Sululta, Adis-Alem, and others. Beside this AUP organizes Annual Architectural Exhibition, where students display and present various works on architecture such as design, modeling, documentaries and project to the public.
                The University’s Health Science Faculty, makes its students engage in various outreach activities. Such as by going to rural community: they determine the number of villages under a health post; sketch the map of health post; survey household data, number of household members, source of water, etc; Obtain health data of the community and other activities.
                Nurse students of the University are assigned to hospitals, where they assist nurses; by doing so they give free service to the hospitals that serve the community. They as well provide health-related education (environment sanitation) to children in nearby schools. Additional to this they check the health of the children they educate.
                <b>Unity University </b>, as it was reflected in its history, was a forward-looking private higher education institution, capable of improving and renewing itself continually. This progressive developmental trend of the institution is still continuing. To this end, the University has expanded its Postgraduate Programs in the areas of Marketing Management, Economics as well as Leadership.
                Currently, Unity delivers eight postgraduate and 13 undergraduate programs, in its different campuses in Addis Ababa and Regional States, through its Regular, Extension and Distance programs; and plans to introduce PhD programs in the future. Beside the degree programs, <b>Unity University </b> offers different kinds of Training Programs as well.
                In its quest for comprehensive quality education, the University has established Unity Academy, which started offering General Education, from KG-Primary, and Secondary level in 2013/14 Academic Year. The very idea of the Academy is to integrate higher education institutions with students of higher academic standards. Currently, the Academy has four branches - two in Addis Ababa, Gerji, and Keranyo, and two in Oromiya Region State: in Burayu and in Adama.
                </p>
          </div>
        </div>
      </div>
@endsection
